### ISSUE TITLE
request stable release of Cache VOL

### ISSUE THREAD

**Issue by wkliao** [hpc-io/vol-cache#22]
I am encountered errors below while testing Log VOL.
```
[CACHE_VOL] ERROR: cache VOL requires MPI to             be initialized with MPI_THREAD_MULTIPLE.             Please use MPI_Init_thread
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
```
It appears that Cache VOL added this requirement recently in its develop branch.

May I suggest to start making releases of Cache VOL?
So other libraries or applications can use the stable versions to run.

**Comment by zhenghh04** [comment]
Thank you @wkliao for reporting this. Yes, I added this recently because of the requirement of Async VOL. We will have a release by the end of this month.

**Comment by wkliao** [comment]
I suggest to wait for all bugs fixed before making release 1.3.
I am encountering a compilation error when using the latest develop branch 4f54ae6100fcfd21ee4f612ec91f8942e55eaa3d
Error message is given below. It should be an easy fix.
```
make
...
[  9%] Building C object src/CMakeFiles/h5cache_vol.dir/cache_utils.c.o
vol-cache/src/cache_utils.c: In function ‘rmdirRecursive’:
vol-cache/src/cache_utils.c:163:13: error: ‘msg’ undeclared (first use in this function)
     sprintf(msg, "remove_cache filepath: %s", filepath);
             ^~~
```

**Comment by wkliao** [comment]
Got an error when testing the latest develop branch 46eab07623a57ce9af3654d9584239c6b20ca915

Test program: [attr.cpp](https://github.com/DataLib-ECP/vol-log-based/blob/master/tests/basic/attr.cpp)

Compile command:
```
mpicxx -g -O0 -Wall  -I/homes/wkliao/HDF5/1.14.1-2/include  -L/homes/wkliao/HDF5/1.14.1-2/lib  attr.cpp  -lhdf5 -o attr
```

Environment variables:
```
HDF5_VOL_CONNECTOR=cache_ext config=cache.cfg;under_vol=0;under_info={}
HDF5_PLUGIN_PATH=/homes/wkliao/CACHE_VOL/lib
```

Run command:
```
mpiexec -n 4 ./attr
```

Coredump trace:
```
#0  __GI___libc_free (mem=0xffffffffffffffff) at malloc.c:3159
#1  0x00007f4932b3b9d5 in my_free (file=0x7f4932b3d418 "/homes/wkliao/CACHE_VOL/vol-cache/src/H5VLcache_ext.c", 
    line=1151, func=0x7f4932b3dd40 <__FUNCTION__.29875> "H5VL_cache_ext_term", p=0xffffffffffffffff)
    at /homes/wkliao/CACHE_VOL/vol-cache/utils/debug.c:166
#2  0x00007f4932b2afe5 in H5VL_cache_ext_term () at /homes/wkliao/CACHE_VOL/vol-cache/src/H5VLcache_ext.c:1151
#3  0x00007f49368df0df in H5VL__free_cls (cls=0x170b960, request=<optimized out>)
    at ../../hdf5-1.14.1-2/src/H5VLint.c:289
```
